dataset:
  name: food101
  source: local # Используем локально скачанный датасет
  path: ./data   # Путь к папке, содержащей food-101
  num_classes: 101
train:
  epochs: 5
  batch_size: 16
  shuffle: true
  lr: 0.0001
  weight_decay: 0.01
  t_max: 10
  label_smoothing: 0.05
  gradient_clip: 1.0
  save_best: true
  seed: 42
  manual_seed_enabled: true
  cutmix: true
val:
  batch_size: 8
  shuffle: false
transforms:
  common:
    resize: 224
    mean:
    - 0.5450310707092285
    - 0.4435403347015381
    - 0.3436422348022461
    std:
    - 0.2694936692714691
    - 0.27188628911972046
    - 0.2766088843345642
  train:
    horizontal_flip_p: 0.5
    random_rotation_deg: 15
    random_crop_scale:
    - 0.8
    - 1.0
    color_jitter:
      brightness: 0.2
      contrast: 0.2
      saturation: 0.2
    gaussian_noise:
      mean: 0.0
      std: 0.01
    cutmix:
      alpha: 1.0
      prob: 0.5
  val: null
hardware:
  num_workers: 0
  pin_memory: false
  grad_accum_steps: 1
  device: cpu