_base_: base.yaml

model:
  model_type: custom
  custom_model_type: cnn
  in_channels: 3
  num_classes: 101
  stem_channels: 64
  stem_conv_kernel_size: 7
  stem_conv_stride: 2
  stem_conv_padding: 3
  stem_pool_kernel_size: 3
  stem_pool_stride: 2
  stem_pool_padding: 1
  block_channels: [64, 128, 256, 512]
  block_strides: [1, 2, 2, 2]
  convs_per_block: [2, 3, 3, 2]
  use_skip_per_block: [True, True, True, True]
  hidden_dims: [1024, 512]
  dropout: 0.3
  dropout_rates_per_block: [0.1, 0.1, 0.2, 0.2]

train:
  lr: 1e-3
  epochs: 10
  batch_size: 256
  optimizer: adamw
  weight_decay: 0.0001
  scheduler:
    name: cosine
  save_dir: ./checkpoints
  save_best: true

hardware:
  num_workers: 8
  pin_memory: false
  grad_accum_steps: 1
  device: cuda
