_base_: base.yaml

model:
  model_type: custom
  custom_model_type: cnn
  num_classes: 101
  in_channels: 3
  stem_channels: 64
  stem_conv_kernel_size: 7
  stem_conv_stride: 2
  stem_conv_padding: 3
  stem_pool_kernel_size: 3
  stem_pool_stride: 2
  stem_pool_padding: 1
  dropout: 0.3 # Фиксированный dropout для поиска архитектуры

train:
  batch_size: 64
  lr: 3e-4
  optimizer: adamw
  weight_decay: 0.01
  scheduler:
    name: cosine
  save_dir: ./checkpoints
  save_best: true

hardware:
  num_workers: 8
  pin_memory: false
  grad_accum_steps: 4
  device: cuda

nas:
  # Общие параметры убраны отсюда и перенесены в каждый этап
  custom_score:
    weights:
      acc: 1.0
      num_params: -0.2
      time_per_epoch: -0.2
    targets:
      num_params: 25000000
      time_per_epoch: 600

  architecture_search:
    direction: maximize
    sampler: TPESampler
    pruner: MedianPruner
    sampler_params:
      n_startup_trials: 10
    pruner_params:
      n_warmup_steps: 7
    num_trials: 1
    epochs_per_trial: 10
    model_params: # Переименовано из params
      block_channels:
        type: list_int
        num_blocks: 4
        range_per_block: [32, 512]
      block_strides:
        type: list_categorical
        num_blocks: 4
        options_per_block: [1, 2]
      convs_per_block:
        type: list_int
        num_blocks: 4
        range_per_block: [1, 3]
      use_skip_per_block:
        type: list_categorical
        num_blocks: 4
        options_per_block: [true, false]
      dropout_rates_per_block:
        type: list_float
        num_blocks: 4
        range_per_block: [0.0, 0.3]
      hidden_dims:
        type: list_int
        num_blocks: 2
        range_per_block: [256, 1024]

  hyperparameters_search:
    direction: maximize
    sampler: TPESampler
    pruner: MedianPruner
    sampler_params:
      n_startup_trials: 10
    pruner_params:
      n_warmup_steps: 7
    num_trials: 1
    epochs_per_trial: 10
    hyper_params: # Переименовано из params
      lr:
        type: float
        range: [1e-5, 1e-3]
        log: true
      dropout:
        type: float
        range: [0.0, 0.3]
      weight_decay:
        type: float
        range: [1e-4, 1e-2]
        log: true
      batch_size:
        type: categorical
        options: [16, 32, 64] # Изменено с [8, 16]