_base_: base.yaml

model:
  model_type: custom
  custom_model_type: vit
  num_classes: 101
  image_size: 224
  dropout: 0.1  # Фиксированный dropout для поиска архитектуры

train:
  batch_size: 64
  lr: 3e-4
  optimizer: adamw
  weight_decay: 0.01
  scheduler:
    name: cosine
  save_dir: ./checkpoints
  save_best: true

hardware:
  num_workers: 8
  pin_memory: false
  grad_accum_steps: 4
  device: cuda

nas:
  # Общие параметры убраны отсюда и перенесены в каждый этап
  custom_score:
    weights:
      acc: 1.0
      num_params: -0.2
      time_per_epoch: -0.2
    targets:
      num_params: 25000000
      time_per_epoch: 600

  architecture_search:
    direction: maximize
    sampler: TPESampler
    pruner: MedianPruner
    sampler_params:
      n_startup_trials: 10
    pruner_params:
      n_warmup_steps: 7
    num_trials: 1
    epochs_per_trial: 10
    fallback_dim: 768      # Перенесено сюда
    fallback_heads: 12     # Перенесено сюда
    model_params:  # Переименовано из params
      heads:
        type: int
        range: [6, 12]
      dim:
        type: int
        range: [384, 512]
      depth:
        type: int
        range: [6, 10]
      mlp_ratio:
        type: float
        range: [1.0, 3.0]
      patch_size:
        type: categorical
        options: [14, 16]

  hyperparameters_search:
    direction: maximize
    sampler: TPESampler
    pruner: MedianPruner
    sampler_params:
      n_startup_trials: 10
    pruner_params:
      n_warmup_steps: 7
    num_trials: 1
    epochs_per_trial: 10
    hyper_params: # Переименовано из params
      lr:
        type: float
        range: [1e-5, 1e-3]
        log: true
      dropout:
        type: float
        range: [0.0, 0.3]
      weight_decay:
        type: float
        range: [1e-4, 1e-2]
        log: true
      batch_size:
        type: categorical
        options: [16, 32, 64] # Изменено с [8, 16]